#!/usr/bin/env bun

/**
 * Apply Migration 0011: Course Correct Remove Task Template
 * Story 2.2.5.1
 * 
 * This script manually applies the SQL migration since it was created manually
 * rather than generated by Drizzle.
 */

import postgres from "postgres";
import { resolve } from "path";
import { config } from "dotenv";
import { readFileSync } from "fs";

// Load environment variables
config({ path: resolve(import.meta.dir, "../../../apps/api/.env") });

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error("❌ DATABASE_URL environment variable not set");
  process.exit(1);
}

const client = postgres(DATABASE_URL, { max: 1 });

console.log("\n🔄 Applying Migration 0011: Course Correct Remove Task Template...\n");

try {
  // Read the migration SQL file
  const migrationSQL = readFileSync(
    resolve(import.meta.dir, "../migrations/0011_course_correct_remove_task_template.sql"),
    "utf-8"
  );

  console.log("📄 Migration file loaded successfully");
  console.log("⚠️  This will:");
  console.log("   - DROP task_template table");
  console.log("   - Modify task_instance table structure");
  console.log("   - Update indexes and constraints\n");

  // Confirm before proceeding
  console.log("Press Ctrl+C within 3 seconds to cancel...");
  await new Promise((resolve) => setTimeout(resolve, 3000));

  console.log("\n🚀 Executing migration SQL...\n");

  // Execute the migration
  await client.unsafe(migrationSQL);

  console.log("✅ Migration applied successfully!\n");

  // Verify the changes
  console.log("🔍 Verifying changes...\n");

  // Check task_template doesn't exist
  try {
    await client`SELECT 1 FROM task_template LIMIT 1`;
    console.error("❌ ERROR: task_template table still exists!");
    process.exit(1);
  } catch (error: any) {
    if (error.message.includes("does not exist")) {
      console.log("✅ task_template table successfully removed");
    } else {
      throw error;
    }
  }

  // Check task_instance has new columns
  const taskInstanceColumns = await client`
    SELECT column_name 
    FROM information_schema.columns 
    WHERE table_name = 'task_instance'
  `;
  const columnNames = taskInstanceColumns.map((col: any) => col.column_name);

  const requiredColumns = [
    "assignee_type",
    "assignee_role",
    "assignee_user_id",
    "completion_time_days",
    "due_at",
  ];

  let allColumnsPresent = true;
  for (const col of requiredColumns) {
    if (columnNames.includes(col)) {
      console.log(`✅ Column '${col}' added`);
    } else {
      console.error(`❌ Column '${col}' missing`);
      allColumnsPresent = false;
    }
  }

  // Check old columns removed
  const removedColumns = ["task_template_id", "assigned_to", "due_date"];
  for (const col of removedColumns) {
    if (!columnNames.includes(col)) {
      console.log(`✅ Column '${col}' removed`);
    } else {
      console.error(`❌ Column '${col}' still exists (should be removed)`);
      allColumnsPresent = false;
    }
  }

  if (allColumnsPresent) {
    console.log("\n✅ All verification checks passed!");
    console.log("\n📝 Next steps:");
    console.log("   1. Run: bun test packages/db/src/schema/__tests__/task-instance-runtime.test.ts");
    console.log("   2. Verify in Supabase SQL Editor if needed");
  } else {
    console.error("\n❌ Some verification checks failed!");
    process.exit(1);
  }

} catch (error) {
  console.error("\n❌ Migration failed:");
  console.error(error);
  process.exit(1);
} finally {
  await client.end();
}

